# Generated by Django 4.1.3 on 2022-11-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regmodel',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
