# Generated by Django 4.1.3 on 2022-11-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
