# Generated by Django 4.1.3 on 2022-11-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_regmodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptNo', models.IntegerField(max_length=50)),
                ('DeptName', models.CharField(max_length=100)),
                ('DeptDescription', models.CharField(max_length=120)),
            ],
        ),
    ]
