# Generated by Django 4.1.3 on 2022-11-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('pic', models.ImageField(null=True, upload_to='profilepic')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='DeptNo',
            field=models.IntegerField(),
        ),
    ]
